packages:
  - "doc"
  - "packages/*"
  - "examples/*"
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@mlightcad/common@1.12.5'
  - '@mlightcad/data-model@1.12.5'
  - '@mlightcad/geometry-engine@3.12.5'
  - '@mlightcad/graphic-interface@3.12.5'
